baseURL = "https://mattr.github.io"
languageCode = "en-us"
title = "Content Security Policy Presentation"
theme = "hugo-webslides"

[params.webslides]
banner = false
slideshow = true
vertical = false
autoslide = false
changeOnClick = false
disableLoop = false
minWheelDelta = 40
disableNavigateOnScroll = false
scrollWait = 450
slideOffset = 50
hideIndex = false

[markup]
defaultMarkdownHandler = "blackfriday"

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true